// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("AhoCorasick.Net")]
[assembly: AssemblyDescriptionAttribute("Implementation of Aho-Corasick algorithm on .NET")]
[assembly: AssemblyCopyrightAttribute("Copyright � 2015")]
[assembly: GuidAttribute("7e918fef-c4dc-4dc4-b366-f2fc38eced4c")]
[assembly: AssemblyProductAttribute("AhoCorasick.Net")]
[assembly: AssemblyVersionAttribute("0.5.0.0")]
[assembly: AssemblyFileVersionAttribute("0.5.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.5.0.0";
    }
}
